#!/usr/bin/env python3
import sys
sys.path.append('~/catkin_ws/src/senseglove_ros_ws/src/senseglove/senseglove_finger_distance/src/senseglove_finger_distance')
import senseglove_finger_distance.haptics_node_action_interface

if __name__ == '__main__':
    senseglove_finger_distance.haptics_node_action_interface.main()
