#!/usr/bin/env python3

import sys
sys.path.append('~/catkin_ws/src/senseglove_ros_ws/src/senseglove/senseglove_finger_distance/src/senseglove_finger_distance')
import senseglove_finger_distance.finger_distance_node

if __name__ == '__main__':
    senseglove_finger_distance.finger_distance_node.main(sys.argv[1], sys.argv[2])